# Generated by Django 4.1.6 on 2023-02-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jogadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.TextField(max_length=255)),
                ("time_principal", models.TextField()),
                ("gols_na_carreira", models.FloatField()),
                ("ainda_joga", models.BooleanField(default=False)),
            ],
        ),
    ]
