# Generated by Django 4.1.6 on 2023-02-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lista_jogadores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jogadores",
            name="principal_titulo",
            field=models.BooleanField(default=True),
        ),
    ]
