# Generated by Django 4.1.6 on 2023-02-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lista_jogadores",
            "0003_alter_jogadores_ainda_joga_alter_jogadores_nome_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Melhores_Do_Brasil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.TextField()),
                ("time_principal", models.TextField(default=250)),
                ("gols_na_carreira", models.FloatField()),
                ("principal_titulo", models.TextField(default=250)),
                ("ainda_joga", models.BooleanField(default=True)),
            ],
        ),
    ]
