# Generated by Django 4.1.6 on 2023-02-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lista_jogadores", "0004_melhores_do_brasil"),
    ]

    operations = [
        migrations.AddField(
            model_name="melhores_do_brasil",
            name="extras",
            field=models.TextField(default=1000),
        ),
    ]
