# Generated by Django 4.1.6 on 2023-02-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lista_jogadores", "0005_melhores_do_brasil_extras"),
    ]

    operations = [
        migrations.CreateModel(
            name="Melhores_Da_Historia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.TextField()),
                ("time_principal", models.TextField(default=250)),
                ("gols_na_carreira", models.FloatField()),
                ("principal_titulo", models.TextField(default=250)),
                ("ainda_joga", models.BooleanField(default=True)),
                ("extras", models.TextField(default=1000)),
            ],
        ),
        migrations.DeleteModel(name="Jogadores",),
    ]
