# Generated by Django 4.1.6 on 2023-02-10 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lista_jogadores", "0006_melhores_da_historia_delete_jogadores"),
    ]

    operations = [
        migrations.RenameField(
            model_name="melhores_da_historia", old_name="extras", new_name="info",
        ),
    ]
