# Generated by Django 4.1.6 on 2023-02-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lista_jogadores", "0007_rename_extras_melhores_da_historia_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="melhores_da_historia",
            name="info",
            field=models.TextField(default=250),
        ),
    ]
