# Generated by Django 4.1.6 on 2023-02-11 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lista_jogadores", "0008_alter_melhores_da_historia_info"),
    ]

    operations = [
        migrations.RenameField(
            model_name="melhores_da_historia", old_name="info", new_name="gol",
        ),
    ]
