# Generated by Django 4.1.6 on 2023-02-11 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lista_jogadores", "0009_rename_info_melhores_da_historia_gol"),
    ]

    operations = [
        migrations.RenameField(
            model_name="melhores_da_historia", old_name="gol", new_name="info",
        ),
    ]
